[package]
name = "peep"
version = "0.1.2"
authors = ["ryochack <ryochack@gmail.com>"]

[dependencies]
getopts = "0.2"
termios = "0.3"
termion = "1.5"
ctrlc = "3.1"
regex = "1.0"
libc = "0.2"
nix = "0.11"
mio = "0.6"
unicode-width = "0.1"

