name: test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, nightly]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all -- --test-threads=1
